python ./run_summarization.py \
    --model_name_or_path t5-small \
    --do_train True\
    --do_predict True\
    --train_file ./data/all_train.csv \
    --test_file ./data/all_test.csv \
    --source_prefix "Generate a description of the following university course: " \
    --max_source_length 128 \
    --max_target_length 1024 \
    --num_train_epochs 10\
    --optim adafactor\
    --lr_scheduler_type constant\
    --learning_rate 1e-3\
    --output_dir ./small_all_10_lr \
    --overwrite_output_dir True \
    --per_device_train_batch_size=2 \
    --per_device_eval_batch_size=4 \
    --predict_with_generate True\
    --save_strategy no\
    --logging_steps 3000\
    --run_name small_all_10_lr